CC = g++
CFLAGS = -std=c++14
TARGET = HidatoSolver
SOURCES = main.cpp \
          Point.cpp \
          Element.cpp \
					HidatoSolver.cpp \
					PuzzleManager.cpp \

all:
	$(CC) $(CFLAGS) -o $(TARGET) $(SOURCES)

clean:
	rm -rf *.o $(TARGET)
